STRTOUL macro is not support non-C99 and non-C11 mode. Therefore, if this was compiled without "-std=gnu99" option, we get the following error.
----
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
----

This fixes syntax of STRTOUL macro. And this changes so that it can be compiled
when C99 or C11 mode has not been specified.

Signed-off-by: Akira Mitsui <murase.syuka@gmail.com>